### ISSUE TITLE
CPU Memory Usage Continually Increases During Training

### ISSUE THREAD

**Issue by hytu99** [Orange-OpenSource/Cool-Chic#12]
Hi, I'm training cool-chic video codec with frames of size 1920x1080. I've encountered an issue where CPU memory usage keeps increasing during training, even when processing 5 frames (see the image below). As a result, I cannot set a larger GOP (e.g., intra_period=32) due to memory limitations.

![Image](https://github.com/user-attachments/assets/766fa9e0-f66f-4240-8232-95ceeb09a9d0)

Each frame is trained independently without gradient propagation, using at most two reference frames at a time. I expected the memory usage to stabilize, but it continues to grow significantly. How can I optimize the code to prevent this memory issue when training with a larger GOP?

**Comment by theoladune** [comment]
Hi,


Short disclaimer: Cool-chic code base has undergone quite a lot of changes since the Cool-chic 3.1 video version. Some issues, including ones related to memory consumption, might have been solved in more recent versions. While we've temporarily disabled video coding for more recent versions (from 3.2 to the latest 3.4), Cool-chic video compression is still under active development and we'll release a better version of Cool-chic video in the following months :).

That being said, I think this particular issue can be solved quite easily.

### Separate frame-wise training

There is a simple workaround for this memory increase, which consists in ending the python script after each frame have been encoded and then relaunching it. There is already a saving/loading mechanism implemented in the code. After each frame is encoded, a ``video_encoder.pt`` file is saved to store the train model:

```python
# From src/models/video_encoder.py, line 207
# Training is over for this frame. Save the model!
self.save(f'{workdir}video_encoder.pt')
```

And launching the ``encode.py`` script with a given ``workdir`` searches for a file named ``workdir/video_encoder.pt``. If one is found, the model is loaded and the training resume from where it ended.

```python
# From src/encode.py, line 155
# Load model is we find one. Resume training
path_video_encoder = f'{workdir}video_encoder.pt'
if os.path.exists(path_video_encoder):
    video_encoder = load_video_encoder(path_video_encoder)
```

So the workaround would be to add a ``sys.exit(0)`` to the first code snipped above so that training ends after each frame. Then you could write a short script to encode the frame one after the other.

```python
# Modified code snippet rom src/models/video_encoder.py, line 207
# Training is over for this frame. Save the model!
self.save(f'{workdir}video_encoder.pt')
# End training each time a frame is encoded
sys.exit(0)
```

### Bumping PyTorch version

It seems that I noticed in the past that more recent pytorch versions can help reducing the memory consumption. You could try using something more up-to-date than the required ``2.0.1``.

Hope this helps!

**Comment by hytu99** [comment]
Thank you for the detailed response!
I followed your suggestions, and they worked perfectly. **Separate frame-wise training** effectively solved the memory issue.  I really appreciate your help!
