### ISSUE TITLE
Anomalous Encoding Results with test/test-workdir/video_encoder.pt

### ISSUE THREAD

**Issue by pxBang** [Orange-OpenSource/Cool-Chic#14]
# Requirement:

I aim to use the existing test/test-workdir/video_encoder.pt file to encode some PPM files, allowing me to quickly evaluate the model's performance without having to train it myself.

# Scenario:

I moved test/test-workdir/video_encoder.pt to the my_temporary_workdir directory. Then, I executed the following command:

```python coolchic/encode.py --input=./house_768x512.ppm --output=./house_768x512.cool --workdir=./my_temporary_workdir/```

Afterwards, I ran:

```python coolchic/decode.py -i=house_768x512.cool -o=768x512_12271645.ppm```

# Issue:

My encoding input path was ./house_768x512.ppm, which is an image of a house. 

![Image](https://github.com/user-attachments/assets/be66b5e6-5d46-4886-94df-94e52beb62f3)

However, the final decoded output image, 768x512_12271645.ppm, turned out to be a picture of a Black girl, leaving me quite puzzled.

![Image](https://github.com/user-attachments/assets/ef7049a0-a3b2-4d8e-9a5c-f21c63312c14)

# Hypothesis:

Could it be that the .pt file already contains information about the input image? Is it possible that a single .pt file can only correspond to one specific image?

# How to Address the Requirement:

I would greatly appreciate your guidance on how to use a trained .pt file to encode different input photos. I am very much looking forward to your response! Thank you!

**Comment by theoladune** [comment]
Hi 👋 

## Short answer

Your hypothesis is correct: one `video_encoder.pt` does correspond to a **single** image at a **single** rate point. Here what happens is that your `workdir` already contains a `video_encoder.pt` with some information relative to the image it represents. So you've got to either change your `workdir` or delete the `video_encoder.pt`.

## Longer answer

### There is no pre-trained model...

Since Cool-chic is an overfitted codec, there is no such thing as a _pre-trained_ model. Each `video_encoder.pt` corresponds to a single image at a single rate target. Indeed, the `video_encoder.pt` is a by-product of the encoding and is generated alongside a `bitstream.cool` file corresponding to the compressed representation of the image and ready to be decoded into something like a `decoded.ppm` image.

### But there are some pre-encoded images

If you want to quickly check the compression performance of Cool-chic on some well-known datasets (Kodak, CLIC20, JVET sequences), we provide some already encoded bitstreams as explained [in the Cool-chic documentation](https://orange-opensource.github.io/Cool-Chic/getting_started/results.html#reproduce-our-current-best-results). These bitstreams were obtained by training one model for each image and rate target. There are ready to be decoded and you can measure the size of the bitstream and the reconstruction quality to assess Cool-chic compression performance.

### You can also encode your own images quite easily

If you want to encode your own images, you can do as indicated in the [encoding documentation](https://orange-opensource.github.io/Cool-Chic/encoding/overview.html#overview). Encoding an image implies training a tiny neural network to overfit the actual image you're encoding. It lasts a few minutes depending on your GPU, the size of the image and the encoding preset.

#

I hope this helps! :wink:

**Comment by pxBang** [comment]
Thank you very much for your response; it has clarified my confusion. I will train the model on a GPU to overfit the images in order to evaluate the model's performance. Once again, thank you for your patient answers.
