### ISSUE TITLE
Perceptive COOL-CHIC and COOL-CHICv2 results

### ISSUE THREAD

**Issue by aegroto** [Orange-OpenSource/Cool-Chic#2]
Hello, thanks for sharing such a detailed codebase and your results with the community. I wonder if the current results are the ones obtained by COOL-CHICv2 or by the older version. I guess those derive from the v2 paper, if so could you please confirm me that the older ones from the ICCV paper in TSV format are [those ones?](https://github.com/Orange-OpenSource/Cool-Chic/blob/47d9ebf03631239f38852a6d8a8842437c85f1bc/results/kodak/raw_results.tsv) Thanks.

Also, do you plan to share results for perceptive metrics such as MS-SSIM and LPIPS? Thanks in advance.

**Comment by theoladune** [comment]
Hello,

The results currently present in /results/ are indeed from Cool-chicv2. They can be recomputed by decoding the bitstreams provided alongside the result file. The older commit that you mention contains the results in line with the ICCV paper.

Since we provide the bitstreams for the compressed images, feel free to decode them and compute any perceptive quality metrics :).

Théo

**Comment by aegroto** [comment]
Thanks for your quick answer! I will calculate the metrics myself as soon as possible.
