### ISSUE TITLE
encode/decode configs for the video codec

### ISSUE THREAD

**Issue by audreyeternal** [Orange-OpenSource/Cool-Chic#9]
Hi, thank you for the impressive work! 

TBH, I nearly have no idea of the video codec. After investigating a little bit of the codebase, I couldn't find the encoding/decoding configs for the video. So I want to know how to determine the `intra_period` and `p_period`? (which is required by `CodingStructure`) And do I need to change other parameters if I use the provided config files (e.g. enc/medium.cfg, dec/mop.cfg) for the video codec? Thank you!

**Comment by theoladune** [comment]
Hi, thanks for your interest in our work!

For the current version (3.2), we've temporarily disabled video coding as it is undergoing an important reworking which will be released in the following months. If you want to use Cool-chic for video coding as in the paper [Cool-chic video: Learned video coding with 800 parameters, Leguay et al.](https://arxiv.org/pdf/2402.03179), you have to revert to the previous Cool-chic version using `git clone --branch v3.1 https://github.com/Orange-OpenSource/Cool-Chic.git`.

⚠️ Everything below is valid only for Cool-chic 3.1 ⚠️

### Coding structure

Regarding the parameterization of the coding structure, it works as follows.

Cool-chic always encodes a Group Of Pictures (GOP), consisting in 1 intra frame followed by 0 to 255 inter frame(s).

**Intra period**

A GOP starts with an intra frame and followed by an arbitrary number of inter (P or B) frames. The number of frames in the GOP and the number of frames encoded by Cool-chic is thus: intra period + 1:

`# This codes 9 frames from the video`
`# number_of_coded_frames = number_of_frames_in_gop = intra_period + 1`
`(venv) python3 src/encode.py --intra_period=8 --input=xxx.yuv`




**P-period** 

Both GOPs below have the same `--intra_period=8` but have a different `--p_period`

`# A low-delay P configuration`
`# I0 ---> P1 ---> P2 ---> P3 ---> P4 ---> P5 ---> P6 ---> P7 ---> P8`
`python3 src/encode.py --intra_period=8 --p_period=1 --input=xxx.yuv`

`# A hierarchichal Random Access configuration`
`# I0 -----------------------------------------------------> P8`
`# \-------------------------> B4 <-------------------------/`
`#  \----------> B2 <---------/ \----------> B6 <----------/`
`#   \--> B1 <--/ \--> B3 <--/   \--> B5 <--/  \--> B7 <--/`
`python3 src/encode.py --intra_period=8 --p_period=8 --input=xxx.yuv`

Note the introduction of the `--p_period` argument in the command line. This sets the distance between the `I0` frame and the successive `P` frames. Reducing the temporal distance alleviates the motion compensation process, which can be useful. It can also enables more complex GOP structure such as:

`# There is no more prediction from I0 to P8. Instead the GOP in split in`
`# half so that there is no inter frame with reference further than --p_period`

`# I0 -----------------------> P4 ------------------------> P8`
`#  \----------> B2 <---------/ \----------> B6 <----------/`
`#   \--> B1 <--/ \--> B3 <--/   \--> B5 <--/  \--> B7 <--/`
`python3 src/encode.py --intra_period=8 --p_period=4 --input=xxx.yuv`

### Configuration files

There is no config file in cool-chic 3.1. However, the script `samples/video/encode_video.sh` gives some relevant parameters to encode video. You might want to set `--n_itr` to 10000 to have better compression performance. Change the `--intra_period` and  `--p_period` values according to your needs.

Hope this helps! 🙂

**Comment by audreyeternal** [comment]
Great, thank you for the quick reply!

I was actually stuck at the encoding step for several hours before I realized that I needed to change the output channel of `layers_synthesis` in cfg/dec/mop.cfg from 3 to X. It seems to be running now, but does this mean it won't work, even though it's running, since you mentioned that the video codec only functions correctly in version 3.1?

By the way, I now understand all the concepts. Thanks again for your help!

**Comment by theoladune** [comment]
In the current version (3.2), you'll only be able to encode video i.e. overfit one Cool-chic for each frame of the video. That will gives you an estimate of the rate-distortion performance of the system in `workdir/results_best.tsv` and the learned model in `workdir/video_encoder.pt`.  What's not going to work on this version is using the learned `video_encoder.pt` to write an actual bitstream and decode this bitstream with a standalone Cool-chic decoder.

If you just want to assess the codec performance, you can do it with the current version (3.2). If you need to produce a bitstream and send it to a different device for decoding, you have to revert to the previous one (3.1).

PS: good catch changing the configuration files. I'll modify them so that no one will get stuck here in the future. 😉

**Comment by audreyeternal** [comment]
Just to update you, I've successfully implemented the video codec using Cool-Chic version 3.1. However, I have one question: it seems that, at the moment, we can only encode and decode the first GOP. From my understanding, a video typically contains multiple GOPs. Is it possible to encode and decode the entire video rather than just the first GOP? Please let me know if I've missed something. Thank you!

**Comment by theoladune** [comment]
Great to hear that you've managed to make it work using Cool-chic 3.1!

Cool-chic is indeed limited to coding the first GOP of a video. To code several GOPs you could split the video file into smaller files with one file per gop e.g. video.yuv would be splitted in gop1.yuv and gop2.yuv. Then encode separately gop1.yuv and gop2.yuv. A bit rudimentary, but it works!
